name: Deploy on PR merge
on:
  push:
    branches: 
      - main

jobs:
  deploy:
      runs-on: ubuntu-latest
      env: 
        GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      steps:
        - uses: actions/checkout@v2

        - name: Setup git
          run: |
            git config --global user.name "$(git --no-pager log --format=format:'%an' -n 1)"
            git config --global user.email "$(git --no-pager log --format=format:'%ae' -n 1)"

        - name: Set up Nodejs
          uses: actions/setup-node@v1
          with:
            node-version: '12.x'

        - name: Install
          run: npm install
        
        - name: Deploy
          run: npm run deploy
          env:
            CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
            CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}

