name: Deploy on PR merge
on:
  push:
    branches: 
      - main
  repository_dispatch:
    types: [publish-event]

jobs:
  deploy:
      runs-on: ubuntu-latest
      env: 
        GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      steps:
        - uses: actions/checkout@v2

        - name: Set up Nodejs
          uses: actions/setup-node@v1
          with:
            node-version: '12.x'

        - name: Install
          run: npm install

        - name: Build
          env:
            CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
            CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
          run : npm run build

        - name: Deploy 🚀
          uses: JamesIves/github-pages-deploy-action@3.7.1
          with:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            BRANCH: gh-pages
            FOLDER: public
            CLEAN: true